---
title: "LFS_prop_test"
output: html_document
date: "2025-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## Data Analysis

Code block 1 for report:

```{r}
# conducts a left sided proportion test on the difference in employment post and pre treatment
prop.test(c(xempSKPOST + 1, xempSKPRE + 1), c(nempSKPOST + 2, nempSKPRE + 2), alternative = "less", correct = FALSE)
# calculates the observed value of z by square rooting the value of chi-squared
# the observed difference in proportions is negative, so z observed is negative as well
zobsSK = -1 *sqrt(0.74734)
zobsSK
```

Code block 2 for report:

```{r}
# calculates the 95% confidence interval for the difference in proportions
prop.test(c(xempSKPOST + 1, xempSKPRE + 1), c(nempSKPOST + 2, nempSKPRE + 2), conf.level = 0.95, correct = FALSE)$conf
```

Code block 3 for report:

```{r}
# conducts a left sided proportion test on the difference in employment post and pre treatment
prop.test(c(xempABPOST + 1, xempABPRE + 1), c(nempABPOST + 2, nempABPRE + 2), alternative = "less", correct = FALSE)
# calculates the observed value of z by square rooting the value of chi-squared
# the observed difference in proportions is negative, so z observed is negative as well
zobsAB = -1 *sqrt(0.01072)
zobsAB
```

Code block 4 for report:

```{r}
#4 code block for report
# calculates the 95% confidence interval for the difference in proportions
prop.test(c(xempABPOST + 1, xempABPRE + 1), c(nempABPOST + 2, nempABPRE + 2), conf.level = 0.95, correct = FALSE)$conf
```
